HotelReservation/Models/ErrorViewModel.cs
using System;

namespace HotelReservation.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

HotelReservation/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using HotelReservation.Models;

namespace HotelReservation.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

HotelReservation/Controllers/ReservationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace HotelReservation.Controllers
{
    public class ReservationController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult secondStep()
        {
            return View();
        }

        public IActionResult thirdStep()
        {
            return View();
        }
    }
}

HotelReservation/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<h1>Hoş Geldiniz</h1>

HotelReservation/Views/Reservation/Index.cshtml
@{
    ViewData["Title"] = "Reservation Page";
}

<script src="https://unpkg.com/gijgo@1.9.13/js/gijgo.min.js" type="text/javascript"></script>
<link href="https://unpkg.com/gijgo@1.9.13/css/gijgo.min.css" rel="stylesheet" type="text/css" />
<link href="~/css/pages/reservationIndex.css" rel="stylesheet" />

<div class="container" style="margin-top:30px">
    <div class="row">
        <div class="col-sm-5">

            <h3>Rezervasyon İşlemleri </h3>
            <p>Rezervasyonunuzu tamamlamak için adımları takip ediniz.</p>
            <ul class="nav nav-pills flex-column">
                <li class="nav-item col-sm-6">
                    <a class="nav-link" href="#" id="dateMenuLink">Tarih</a>
                </li>
                <li class="nav-item col-sm-6">
                    <a class="nav-link disabled" id="roomMenuLink" href="#">Oda</a>
                </li>
                <li class="nav-item col-sm-6">
                    <a class="nav-link disabled" id="payMenuLink" href="#">Ödeme</a>
                </li>
            </ul>
            <hr class="d-sm-none">
        </div>

        <div class="col-sm-7">

            <h3>1.Adım</h3>
            <p>Lütfen otele giriş tarihini ve çıkış tarihini seçiniz.</p>

            <div class="col-md-6 mb-4">
                <label for="datetimepicker6">Giriş(Check-in) Tarihi:</label>
                <div class="form-group">
                    <div class='input-group date'>
                        <input type="text" id="startingDate" width="276" />
                    </div>
                </div>
            </div>

            <div class="col-md-6 mb-4">
                <label for="endingDate">Çıkış(Check-out) Tarihi:</label>
                <div class="form-group">
                    <div class='input-group date'>
                        <input type="text" id="endingDate" width="276" />
                    </div>
                </div>
            </div>
            <div id="dateIsNullAlert" class="alert alert-danger" data-alert="alert">Tarih alanları boş bırakılamaz.</div>


            <br />

            <div class="row">
                <div class="col-9">
                </div>
                <div class="col-3">
                    <div class="text-right">
                        <button id="passToSecondStep" type="button" class="btn btn-outline-primary">2.Adım</button>
                    </div>
                </div>
            </div>

            <br />

            <div id="secondStepDiv">
                @Html.Partial("secondStep.cshtml")
            </div>

            <br />
            <br />

            <div id="thirdStepDiv">
                @Html.Partial("thirdStep.cshtml")
            </div>


        </div>
    </div>
</div>


<script src="~/js/pages/reservationPages/reservationPage.js"></script>
<script src="~/js/components/datepicker.js"></script>

HotelReservation/Views/Reservation/secondStep.cshtml

<link href="~/css/pages/reservationSecondStep.css" rel="stylesheet" />

<h3>2.Adım</h3>
<p>Lütfen odanızın özelliklerini seçiniz.</p>

<div class="row" id="selectRoomDiv">
    <div class="col-3">
        <label>Oda Tipi:</label>
    </div>
    <div class="col-6">
        <label><input type="checkbox" name="roomTypes" id="standartRoom" class="selectRoomType" value="standartRoom">Standart</label>
        <label><input type="checkbox" name="roomTypes" id="deluxRoom" class="selectRoomType" value="deluxRoom">Delux</label>
        <label><input type="checkbox" name="roomTypes" id="suitRoom" class="selectRoomType" value="suitRoom">Suit</label>
    </div>
</div>
<div class="row" id="selectViewDiv">
    <div class="col-3">
        <label>Manzara Seçimi:</label>
    </div>
    <div class="col-6">
        <label><input type="checkbox" name="viewTypes" id="seaViewRoom" class="selectRoomView" value="seaViewRoom">Deniz</label>
        <label><input type="checkbox" name="viewTypes" id="ovarlandViewRoom" class="selectRoomView" value="ovarlandViewRoom">Kara</label>
    </div>
</div>
<br />
<br />

<div class="row">
    <div class="col-3">
        <div class="text-left">
            <button id="backToFirstStepBtn" type="button" class="btn btn-outline-dark">Geri</button>
        </div>
    </div>
    <div class="col-6">

    </div>
    <div class="col-3">
        <div class="text-right">
            <button id="passToThirdStepBtn" type="button" class="btn btn-outline-primary">3.Adım</button>
        </div>
    </div>
</div>
<br />

<div id="checkIsNullAlert" class="alert alert-danger" data-alert="alert">Oda Tipi ve Manzara Seçenekleri boş bırakılamaz.</div>


<script src="~/js/pages/reservationPages/secondStepPage.js"></script>

HotelReservation/Views/Reservation/thirdStep.cshtml
<link href="~/css/pages/component/creditcard.css" rel="stylesheet" />
<link href="~/css/pages/reservationThirdStep.css" rel="stylesheet" />

<h3>3.Adım</h3>
<p>Lütfen ödeme işlemi için gerekli alanları doldurunuz.</p>

<br />

<div id="creditCardFormDiv">
    @Html.Partial("/Views/Shared/components/_CreditCardForm.cshtml")
</div>

<br />

<div id="reservationIsSuccess" class="alert alert-success" data-alert="alert">Rezervasyonunuz başarılı bir şekilde tamamlanmıştır. Size en kısa sürede dönüş yapacağız. Teşekkürler.</div>


<div class="row">
    <div class="col-3">
        <div class="text-left">
            <button type="button" class="btn btn-outline-dark" id="backToSecondStep">Geri</button>
        </div>
    </div>
    <div class="col-6">

    </div>
    <div class="col-3">
        <div class="text-right">
            <button type="button" id="reservationComplateBtn" class="btn btn-outline-primary"> Tamamla</button>
        </div>
    </div>
</div>



<script src="~/js/pages/reservationPages/thirdStepPage.js"></script>

HotelReservation/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Sef Hotel | Sizin Oteliniz</title>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Sef Otel</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Anasayfa</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Reservation" asp-action="Index">Rezervasyon</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">İletişim</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - HotelReservation - Copyright: Sef! All rights reserved. @*<a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>*@
        </div>
    </footer>

</body>
</html>

HotelReservation/Views/Shared/components/_CreditCardForm.cshtml

<link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">

<div class="container">
    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 mx-auto">
            <div class="bg-white rounded-lg shadow-sm p-5">
                <!-- Kredi Kartı Form Tabı Başlangıç -->
                <ul role="tablist" class="nav bg-light nav-pills rounded-pill nav-fill mb-3">
                    <li class="nav-item">
                        <a data-toggle="pill" href="#nav-tab-card" class="nav-link active rounded-pill">
                            <i class="fa fa-credit-card"></i>
                            Kredi Kartı
                        </a>
                    </li>
                    <li class="nav-item">
                        <a data-toggle="pill" href="#nav-tab-paypal" class="nav-link rounded-pill">
                            <i class="fa fa-paypal"></i>
                            Paypal
                        </a>
                    </li>
                    <li class="nav-item">
                        <a data-toggle="pill" href="#nav-tab-bank" class="nav-link rounded-pill">
                            <i class="fa fa-university"></i>
                            Banka Bilgileri
                        </a>
                    </li>
                </ul>
                <!-- Kredi Kartı Form Tabı Bitiş -->


                <div class="tab-content">
                    <!--KRedi Kartı Bilgisi -->
                    <div id="nav-tab-card" class="tab-pane fade show active">
                        <form role="form">
                            <div class="form-group">
                                <label for="username">İsim Soyisim (kart üzerindeki)</label>
                                <input type="text" id="username" name="username" placeholder="Sefa Özel" required class="form-control">
                            </div>
                            <div class="form-group">
                                <label for="cardNumber">Kart Numarası</label>
                                <div class="input-group">
                                    <input type="text" id="cardNumber" name="cardNumber" placeholder="**** **** **** ****" class="form-control" maxlength="16" required>
                                    <div class="input-group-append">
                                        <span class="input-group-text text-muted">
                                            <i class="fa fa-cc-visa mx-1"></i>
                                            <i class="fa fa-cc-amex mx-1"></i>
                                            <i class="fa fa-cc-mastercard mx-1"></i>
                                        </span>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-4 col-md-4 col-lg-4">
                                    <div class="form-group">
                                        <label><span class="hidden-xs">Son Kullanım Tarihi</span></label>
                                        <div class="input-group">
                                            <input type="number" id="cardLastDateMonth" placeholder="Ay" name="" class="form-control" required>
                                            <input type="number" id="cardLastDateYear" placeholder="Yıl" name="" class="form-control" required>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-sm-4 col-md-4 col-lg-4">
                                </div>
                                <div class="col-sm-4 col-md-4 col-lg-4">
                                    <div class="form-group mb-4">
                                        <label data-toggle="tooltip" title="Kartınızın arka tarafında yer alan 3 haneli numara.">
                                            CVV
                                            <i class="fa fa-question-circle"></i>
                                        </label>
                                        <input type="text" id="cardCVV" required class="form-control" maxlength="3">
                                    </div>
                                </div>



                            </div>
                            <button type="button" id="acceptToPayBtn" class="subscribe btn btn-primary btn-block rounded-pill shadow-sm"> Ödemeyi Tamamla  </button>

                            <div id="creditCardIsInfoNull" class="alert alert-danger" data-alert="alert">Kredi Kartı Alanları Eksiksiz Olmalıdır.</div>

                        </form>
                    </div>
                    <!-- Bitiş -->


                    <!-- Paypal  -->
                    <div id="nav-tab-paypal" class="tab-pane fade">
                        <p>Paypal online ödeme yapmanızın kolay bir yoludur.</p>
                        <p>
                            <button type="button" class="btn btn-primary rounded-pill"><i class="fa fa-paypal mr-2"></i>Paypal hesabınıza giriş yapınız</button>
                        </p>
                        <p class="text-muted">
                            Paypal hesabınıza giriş yaparak kolayca ödeme işlemenizi gerçekleştirebilirsiniz.
                        </p>
                    </div>
                    <!-- Bitiş -->


                    <!-- Banka Bilgileri -->
                    <div id="nav-tab-bank" class="tab-pane fade">
                        <h6>Banka Hesap Bilgileri</h6>
                        <dl>
                            <dt>Banka</dt>
                            <dd>Sef Bankası</dd>
                        </dl>
                        <dl>
                            <dt>IBAN Numarası</dt>
                            <dd>TR11 0000 0000 0000 1111 11</dd>
                        </dl>
                        <dl>
                            <dt>Hesap Sahibi</dt>
                            <dd>Sef Otelleri İşletmeciliği A.Ş.</dd>
                        </dl>
                        <p class="text-muted">
                            Ödemeyi HAVALE/EFT yolu ile yukarıda bulunan hesaba gönderebilirsiniz. İşlemi tamamladıktan sonra işlem dekontunu <b>rezervasyon@sefotel.com</b> adresine gönderiniz.
                        </p>
                    </div>
                    <!-- Banka Bilgileri Bitiş -->
                </div>
                <!-- Bitiş -->

            </div>
        </div>
    </div>
</div>

<script src="~/js/components/creditcard.js"></script>